# Generated by Django 5.1.7 on 2025-03-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='categorias',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AddField(
            model_name='personal',
            name='grupo',
            field=models.CharField(default='Admin', max_length=100),
        ),
    ]
