# Generated by Django 5.1.7 on 2025-03-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_personal_categorias_personal_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='categorias',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personal',
            name='grupo',
            field=models.CharField(max_length=100),
        ),
    ]
